# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mUkn0oBIxMs2OVNiZpkjQtvi3CV2lTrN
"""

import os
import json

!pip install -r requirements.txt

from langchain_openai import ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate

working_dir = os.path.dirname(os.path.abspath(__file__))
config_data = json.load(open(f"{working_dir}/config.json"))

OPENAI_API_KEY = config_data.get("OPENAI_API_KEY")
os.environ["OPENAI_API_KEY"] = OPENAI_API_KEY

llm = ChatOpenAI(
    model = "gpt-4o",
    temperature=0
    )

def translate(input_language, output_language, input_text):
  prompt = ChatPromptTemplate.from_messages(
      [
          ("system", "You are a helpful assistant that translates {input_language} to{output_language}.")
          ("human","{input}" )
      ]
  )
  chain = prompt | llm
  response = chain.invoke(
      {
          "input_language": input_language,
          "output_language": output_language,
          "input": input_text,
      }
  )

  return response.content

